### ISSUE TITLE
🚀 Feature: Add a footer section.

### ISSUE THREAD

**Issue by ArunPatel02** [GDSCITM/GDSCITM-official-website#19]
### 📜 Feature Description

The footer section will have redirecting links of all social media accounts of gdsc, join us button and menu list that will scroll the page to the particular section.

### 🎤 Pitch

checkout this design to inspire and create a component https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=684eNs6xDEXUA2GK-1

![image](https://user-images.githubusercontent.com/89798093/212477675-dfba0089-1b97-4956-a6b9-648353488572.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🔖 Have you read the Code of Conduct?

- [X] Please search to see if an issue already exists for the feature you wanna add.

**Comment by apala7778** [comment]
hey i want to work on this. can you assign me this?

**Comment by Yashsharma1911** [comment]
Go ahead @apala7778

**Comment by Yashsharma1911** [comment]
any progress? @apala7778

**Comment by Yashsharma1911** [comment]
don't worry @apala7778, Hey @ArunPatel02 do you have any suggestions on how we can make these lines?

**Comment by ArunPatel02** [comment]
![image](https://user-images.githubusercontent.com/89798093/212982896-7794d644-5dd2-4061-b9db-96d481f915c0.png)

@apala7778 you can create an imaginary box (with overflow: hidden) and inside the join button wrapper (with position: relative ) you can make 4 div (with position absolute) and transform all those 4 div . you can calculate the angle of rotation with the help of JavaScript taking the red line as base and green line as perpendicular.

**Comment by 4-Leafs-Code** [comment]
You could also use the Google developer tools to get a better imitate visual of the lines and the code instead of guessing and complicated math that will scare of newbs or have them push a draft pull request and comment in their code to help them out when their our struggling. Work smarter not harder guys. Good Luck!!

**Comment by ArunPatel02** [comment]
Thank you so much @4-Leafs-Code for your feedback next time we will take care of this.

**Comment by 4-Leafs-Code** [comment]
Lol, I'm not sure if your being sarcastic because I just read my comment and I sound kind of rude. I apologize because I did not mean to sound that way. I've been up all night board just scrolling thru help wanted trying to help people out. But it is really hard and intimidating to brake into coding and you never know someone's experience level, you know. I find it's better to over simplifies then and keep them contributing then to scare them off.

**Comment by devharsh007** [comment]
If its not complete. Please assign it to me too . I have some ideas.

**Comment by Yashsharma1911** [comment]
that would be helpful @devharsh007 yes go ahead

**Comment by Yashsharma1911** [comment]
Thanks for sending words @devharsh007 let's get you assigned new issue which you would like to work let us know how we can help

Also it would be great if you give a suggestion of below survey

- We are thinking to have a weekly meet with contributors to disscus their assigned issues and PR if they are facing any issue so that we can help what do you think 🤔 your suggestion would be appreciated

**Comment by devharsh007** [comment]
Sure i would like to help

**Comment by kamalchakma1** [comment]
Hi I want to work on this issue. Please assign me let me try. Thank you.

**Comment by ArunPatel02** [comment]
> Hi I want to work on this issue. Please assign me let me try. Thank you.
Thank you @kamalchakma1 for showing your interest. Go ahead.

**Comment by kamalchakma1** [comment]
@ArunPatel02 Hi I have added footer and create a pull request. Please check

**Comment by Yashsharma1911** [comment]
This issue fixed in #86 by @kamalchakma1
