### ISSUE TITLE
🐛 Bug Report: Responsiveness for Events section

### ISSUE THREAD

**Issue by sudhanshutech** [GDSCITM/GDSCITM-official-website#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current behavior is at a **1276 px** ratio event section is not responsive and at **816 px** ratio also. The team section is above the event section for under these screen ratios.
![Screenshot (40)](https://user-images.githubusercontent.com/90546692/213917415-99b1343c-5428-4f0f-b6bb-ae412f5f7395.png)

### Expected Behavior

Have a look at the **UI** for the issue 
[Check Figma Design](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=oEpdFbAdYoxhSJau-0)

**Comment by ArunPatel02** [comment]
### Current Behavior

The event section should be responsive for mobile screens.
![image](https://user-images.githubusercontent.com/89798093/214069280-6e1e3826-f577-4109-917d-91a1efb4885f.png)




### Expected Behavior


![image](https://user-images.githubusercontent.com/89798093/214069117-ee74c358-1a3a-4c32-bf74-c0e91a05370c.png)

checkout this design file - [Check Figma Design](https://www.figma.com/file/ZTnjjETRtg8HNV0zufJajF/GDSC?node-id=0%3A1&t=oEpdFbAdYoxhSJau-0)

**Comment by Yashsharma1911** [comment]
Hey @ArunPatel02 create another issue for this problem
