### ISSUE TITLE
🐛 Bug Report: Email gets hide when user types their email

### ISSUE THREAD

**Issue by Yashsharma1911** [GDSCITM/GDSCITM-official-website#6]
👍 Expected behavior
The email of the user should be seen properly

👎 Actual Behavior
![Screenshot 2022-11-18 at 12 00 02 AM](https://user-images.githubusercontent.com/71271069/202530334-6a8cb4a9-ad95-4100-9858-391b537908ea.png)

🎲 Web version
Version 1.0.0

🧱 Your Environment
No response

👀 Have you spent some time to check if this issue has been raised before?
 I checked and didn't find similar issue
🏢 Have you read the [Code of Conduct](https://github.com/GDSCITM/GDSCITM-official-website/blob/main/README.md#contributing)?
 I have read the Code of Conduct

**Comment by NJ-2020** [comment]
Can I solve this issue please?

**Comment by Yashsharma1911** [comment]
Hey @NJ-2020 go-ahead

**Comment by ArunPatel02** [comment]
#11 
## 👍 Expected behavior
The email input by the user should be seen properly on small-screen devices too.

## 👎 Actual Behavior
![image](https://user-images.githubusercontent.com/89798093/202897764-c6fc0565-c45b-4e70-a7c8-ec4d29be1ce5.png) 

🐛 On the small screen, the email is not showing properly as there is a lot of blank space between the red pointer and button, where the user is not able to type.
